### PR TITLE
Replacing "reason" & boolean value for validator with parameters with…

### PR DESCRIPTION
**Pull request by adhmn4**
Replacing "reason" & boolean value for validator with parameters with object that has the parameter's value

### CODE REVIEW

**Comment by rsaenen** [comment]
Thanks, why sometime the `control` has value undefined?
```typescript
expect(maxDate(obj)(control)).toEqual({ maxDate: { value: obj, control: undefined } });
```

**Comment by rsaenen** [comment]
Released with 6.1.0
I have to drop @angular/router depedency, why did you add it to dependencies ?

**Comment by adhmn4** [comment]
It wouldn't build without it, its used in file: src/dev/dev.module.ts

**Comment by rsaenen** [comment]
I would say I had to move this package to devDependencies as it used by demo module.

I will update the readme.

**Pull request merged**
